imports:
- path: project.py

resources:
# CHANGEME: Name of the host project for the Shared VPC
- name: HOST_PROJECT
  type: project.py
  properties:
    # CHANGEME: Change this to your organization ID.
    organization-id: "ORG_ID"
    # CHANGEME: Change the following to your organization's billing account
    billing-account-name: billingAccounts/BILLING_ACCOUNT_ID
    # The apis to enable in the new project.
    # To see the possible APIs, use gcloud CLI: gcloud services list --available
    apis:
    - compute.googleapis.com
    - deploymentmanager.googleapis.com
    - storage-component.googleapis.com
    - monitoring.googleapis.com
    - logging.googleapis.com
    # Makes the service account that Deployment Manager would use
    # in the generated project an admin
    set-dm-service-account-as-owner: true
    # IAM policy on the new project
    iam-policy-patch:
      add:
      - role: roles/viewer
        members:
        # CHANGEME: Change this to your email address
        - user:EMAIL
      - role: roles/compute.networkUser
        members:
        # CHANGEME: Change this to your email address
        - user:EMAIL
      - role: roles/deploymentmanager.editor
        members:
        # CHANGEME: Change this to your email address
        - user:EMAIL
    shared_vpc_host: true
# CHANGEME: Name of the service project for the Shared VPC
- name: SERVICE_PROJECT
  type: project.py
  properties:
    # CHANGEME: Change this to your organization ID.
    organization-id: "ORG_ID"
    # CHANGEME: Change the following to your organization's billing account
    billing-account-name: billingAccounts/BILLING_ACCOUNT_ID
    # The apis to enable in the new project.
    # To see the possible APIs, use gcloud CLI: gcloud services list --available
    apis:
    - compute.googleapis.com
    - deploymentmanager.googleapis.com
    - storage-component.googleapis.com
    - monitoring.googleapis.com
    - logging.googleapis.com
    # Makes the service account that Deployment Manager would use
    # in the generated project an admin
    set-dm-service-account-as-owner: true
    # IAM policy on the new project
    iam-policy-patch:
      add:
      - role: roles/editor
        members:
        # CHANGEME: Change this to your email address
        - user:EMAIL
      - role: roles/compute.admin
        members:
        # CHANGEME: Change this to your email address
        - user:EMAIL
    # CHANGEME: Change this to the name of your host project for the Shared VPC
    shared_vpc_service_of: HOST_PROJECT
